### ISSUE TITLE
java.lang.IllegalArgumentException: ItemID should not be null

### ISSUE THREAD

**Issue by ivanovcorp** [reportportal/example-java-TestNG#8]
Below is the exception RP is throwing.
We are using it as follows: We're building a framework which then is deployed to maven repository(rp dependancy is included in the framework pom). Then we create a new maven project and put our framework as a dependency. Then we create a Test in that new project and pass the ```@Listeners({TestRunnerUI.class, ReportPortalTestNGListener.class})``` and run the tests
then the issue appears, however, when using the listener inside the framework itself ... no problem occurs:
```
java.lang.IllegalArgumentException: ItemID should not be null
    at rp.com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
    at com.epam.reportportal.service.LaunchImpl.finishTestItem(LaunchImpl.java:246)
    at com.epam.reportportal.testng.TestNGService.finishTestMethod(TestNGService.java:157)
    at com.epam.reportportal.testng.BaseTestNGListener.onTestFailure(BaseTestNGListener.java:98)
    at org.testng.internal.Invoker.runTestListeners(Invoker.java:1868)
    at org.testng.internal.Invoker.runTestListeners(Invoker.java:1852)
    at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1268)
    at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
    at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
    at org.testng.TestRunner.privateRun(TestRunner.java:758)
    at org.testng.TestRunner.run(TestRunner.java:613)
    at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
    at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
    at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
    at org.testng.SuiteRunner.run(SuiteRunner.java:240)
    at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
    at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
    at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
    at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
    at org.testng.TestNG.run(TestNG.java:974)
    at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
    at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
the strange thing also here is: at com.epam.reportportal.testng.BaseTestNGListener.onTestFailure(BaseTestNGListener.java:98)
```
why does it mark it as failed, although its not started yet
If you need more details, please contact me: ivan.ivanov@ezbob.com

**Comment by ivanovcorp** [comment]
Problem is in the TestNG version. When you use 6.14.3 the issue appears. 
The issue is fixed when reverting back to 6.13.1.

**Comment by DzmitryHumianiuk** [comment]
try it with TestNG 7.0.0-SNAPSHOT
https://github.com/cbeust/testng/issues/1656#issuecomment-356477013

**Comment by sargissargsyan** [comment]
I still see this issue with 6.13.1
Exception in thread "TestNG-test=Workfront Selenium Suite-84" java.lang.IllegalArgumentException: ItemID should not be null
	at rp.com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
	at com.epam.reportportal.service.LaunchImpl.finishTestItem(LaunchImpl.java:246)
	at com.epam.reportportal.testng.TestNGService.finishTestMethod(TestNGService.java:157)
	at com.epam.reportportal.testng.BaseTestNGListener.onTestFailure(BaseTestNGListener.java:98)
	at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:67)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1379)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1032)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by DzmitryHumianiuk** [comment]
@sargissargsyan is it reproducible with 7.0 version?

**Comment by DzmitryHumianiuk** [comment]
@sargissargsyan can you also decouple small example, which will repeat the same behavior? 
since this stacktrace says nothing.

**Comment by sargissargsyan** [comment]
I will check with version 7 and will send you update tomorrow

**Comment by sargissargsyan** [comment]
@DzmitryHumianiuk actually I am unable to import 7.0.0-SNAPSHOT version to my maven project

**Comment by DzmitryHumianiuk** [comment]
@sargissargsyan i see it's available via gradle build
https://github.com/cbeust/testng/blob/master/build.gradle

**Comment by iKozzz** [comment]
I met same issue with my listener.
At first I had my hooks by implementing 'IHookable' interface
    @Override
    public void run(IHookCallBack callBack, ITestResult testResult) {
        ... before-hooks ...
        // TEST LAUNCH
        callBack.runTestMethod(testResult);
        ... after-hooks ...
    }

I tried to do same thing through 'IInvokedMethodListener' and issue has happened.
    @Override
    public void afterInvocation(IInvokedMethod method, ITestResult testResult) {
    ... after-hooks ...
    }

Summary:
IHookable - is working solution.
Tried with different TestNG versions. Current is '7.0.0-beta1'

**Comment by filland** [comment]
@ivanovcorp @sargissargsyan @iKozzz Could you tell if you still face this issue ? I tried to reproduce it and it works fine.

**Comment by sargissargsyan** [comment]
@filland with TestNG 7 seems it was ok

**Comment by filland** [comment]
@sargissargsyan maybe you have an example that i can use to reproduce the issue ?
